### PR TITLE
Silverstripe 5 support

### PR DESCRIPTION
**Pull request by izzudin96**
A start to support Silverstripe 5

### CODE REVIEW

**Comment by izzudin96** [comment]
Hi @dnsl48, are you able to merge this PR? 

Thanks

**Comment by dnsl48** [comment]
Hi @izzudin96, thank you for the contribution!
Unfortunately, I am no longer a maintainer for this repo. We might need to find out who is.
cc @sminnee @maxime-rainville

**Comment by mlewis-everley** [comment]
> Unfortunately, I am no longer a maintainer for this repo. We might need to find out who is.

I seem to have lost maintainer status too, any ideas @sminnee ?

**Comment by sminnee** [comment]
I've re-sent the invite @mlewis-everley

**Comment by mlewis-everley** [comment]
> I've re-sent the invite @mlewis-everley

Hey @sminnee just saw the invite but it has expired, could you resend?

**Comment by sminnee** [comment]
done!

**Comment by mlewis-everley** [comment]
> done!

Cool, just approved, I am going to try and test this out tomorrow in a Silverstripe 5 site.

**Comment by mlewis-everley** [comment]
OK, just tested this today with a few variations on a mostly vanilla SS5 site. All seems OK to me.

@sminnee are you OK for me to merge this?

**Comment by sminnee** [comment]
Yep, go for it!

**Comment by mlewis-everley** [comment]
Done :-)

**Pull request merged**
